# Generated by Django 4.2.3 on 2023-07-13 12:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_Bill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('InvoiceNumber', models.CharField(max_length=100, null=True)),
                ('CreationDate', models.DateField(blank=True, default=datetime.datetime(2023, 7, 13, 14, 37, 41, 732482))),
                ('InvoiceReason', models.CharField(max_length=100, null=True)),
                ('Designations', models.TextField(null=True)),
                ('Quantities', models.TextField(null=True)),
                ('PriceHT', models.TextField(null=True)),
                ('TVA', models.TextField(null=True)),
                ('AddInformation', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
