# Generated by Django 4.2.3 on 2023-07-15 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('createBill', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_bill',
            name='CreationDate',
        ),
    ]
