# Generated by Django 4.2.3 on 2023-07-15 17:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createBill', '0002_remove_customer_bill_creationdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_bill',
            name='CreationDate',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 7, 15, 17, 47, 34, 312983, tzinfo=datetime.timezone.utc)),
        ),
    ]
