# Generated by Django 4.2.3 on 2023-07-15 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('createBill', '0003_customer_bill_creationdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_bill',
            name='CreationDate',
        ),
    ]
