# Generated by Django 4.2.3 on 2023-07-15 18:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createBill', '0004_remove_customer_bill_creationdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_bill',
            name='CreationDate',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 7, 15, 20, 30, 18, 34473)),
        ),
    ]
